# Generated by Django 4.2.5 on 2023-09-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('relationship_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.relationshipmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blurb', models.CharField(default='', max_length=1000)),
                ('type', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'expired'), (4, 'revoked')], default=1)),
                ('presigned_url', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.customer')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.file')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='relationship_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.relationshipmanager'),
        ),
    ]
